const TYPE = {
    ON_SEARCH_QUERY_PRICE_CHANGED: 'ON_SEARCH_QUERY_PRICE_CHANGED',
    ON_SEARCH_QUERY_GROUP_CHANGED: 'ON_SEARCH_QUERY_GROUP_CHANGED',
    ON_SEARCH_QUERY_CATEGORY_CHANGED: 'ON_SEARCH_QUERY_CATEGORY_CHANGED',
    ON_SEARCH_QUERY_RATING_CHANGED: 'ON_SEARCH_QUERY_RATING_CHANGED',
    ON_SEARCH_QUERY_ORDER_CHANGED: 'ON_SEARCH_QUERY_ORDER_CHANGED',
}

export default TYPE;